source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'ImageExportExtension' do
    pod 'Alamofire', '~> 4.7'
end

target 'ImageExport' do
    pod 'Alamofire', '~> 4.7'
end
